---
title: "CurrentWorkSample"
author: "Jiayi&Isaac"
date: "2022-12-07"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("foreign")
#install.packages("qpcR")  
#install.packages("devtools")
#install.packages("GGally")
#install.packages("glmnet")
#install.packages("hablar")
```

```{r}
library(dplyr)
library(foreign)
library("qpcR") 
library(ggplot2)
library(ggcorrplot)
library(GGally)
library(glmnet)
library(class)
library(hablar)
library(randomForest)

```

```{r}
## Dataset
V0 <- readRDS("complete.rds")
V0 = V0 %>% rename(SEQN = seqn)
V0 <- V0[,c("SEQN","ridreth1","total_na")]
```

```{r}
V1 <- readRDS("best_forward_revised.rds")
V1 = V1 %>% rename(SEQN = seqn)
```

```{r}
BPX2015_2016<-read.xport("BPX2015_2016.XPT")
BPX2015_2016 <- BPX2015_2016[c('SEQN','BPXDI1','BPXSY1')]
```

```{r}
data2015_2016 <- qpcR:::cbind.na(V1, BPX2015_2016, V0, by = 'SEQN')
```

```{r}
data2015_2016[is.na(data2015_2016)] = 0
```

```{r}
write.csv(data2015_2016,"C:/Users/elsie/OneDrive/Documents/data2015_2016.csv",
          row.names=FALSE)
```

```{r}
## Visualization
```

```{r}
data2015_2016 = read.csv('data2015_2016.csv')
```

```{r}
data2015_2016_corr <- cor(data2015_2016, use="complete.obs")
round(data2015_2016_corr,2)
ggcorrplot(data2015_2016_corr)
```

```{r}
#ggcorrplot(data2015_2016_corr, hc.order = TRUE, type = "lower",lab = FALSE)
```

```{r}
ggpairs(data2015_2016, colour = "cyl",
    upper = list(continuous = wrap("cor", size = 1)))
labs(title = "1") +
  theme_bw()
```

```{r}
result0 <- lm(data2015_2016$BPXSY1~data2015_2016$ridageyr+data2015_2016$bmxbmi+data2015_2016$riagendr+data2015_2016$fsd855+data2015_2016$diq010+data2015_2016$ridreth1+data2015_2016$total_na)
summary(result0)
anova(result0)
confint(result0)
plot(result0)
```

```{r}
Sample1 = data2015_2016[sample(ncol(data2015_2016), 5)]
```

```{r}
Sample1 = ggpairs(Sample1, colour = "cyl",
    upper = list(continuous = wrap("cor", size = 3)))
labs(title = "1") +
  theme_bw()
Sample1
```

```{r}
result1 <- lm(data2015_2016$BPXSY1~data2015_2016$section_H+data2015_2016$section_I)
summary(result1)
anova(result1)
confint(result1)
plot(result1)
```

```{r}
##KNN

hist(data2015_2016$BPXSY1)
summary(data2015_2016$BPXSY1)
sort(data2015_2016$BPXSY1)
```

```{r}
data2015_2016 <- within(data2015_2016, {   
  BPXSY1_1 <- NA 
  BPXSY1_1[BPXSY1 <= 120] <- "Normal"
  BPXSY1_1[BPXSY1 >= 120 & BPXSY1 < 140] <- "prehypertension"
  BPXSY1_1[BPXSY1 >= 140] <- "hypertension"
   } )
```

```{r}
data2015_2016$BPXSY1_1 <- as.numeric(as.integer(factor(data2015_2016$BPXSY1_1)))
```

```{r}
set.seed(12223)
tr <- sample(nrow(data2015_2016), nrow(data2015_2016)*.5)
```

```{r}
train<-data2015_2016[tr, ]
test<-data2015_2016[-tr,]
k <- 3
```

```{r}
knnres <- knn(train, test, data2015_2016$BPXSY1_1[tr])
head(knnres)
```

```{r}
table(knnres, data2015_2016$BPXSY1_1[-tr])
mean(knnres == data2015_2016$BPXSY1_1[-tr])
```

```{r}
## another way for KNN

index <- sample(1:nrow(data2015_2016),as.integer(0.7*nrow(data2015_2016)))
```

```{r}
set.seed(123)
train <- data2015_2016[index,-5]
test <- data2015_2016[-index,-5]
cl <- data2015_2016[index,5]
k <- 3
```

```{r}
pre <- knn(train = train, test = test, cl = cl, k = k);
pre <- knn(train = train, test = test, cl = cl, k = k, prob = T);
```

```{r}
table(pre, data2015_2016$BPXSY1_1[-index])
```

```{r}
## a way to check test KNN from Google

vknn = function(v, data2015_2016, cl, k){
  grps = cut(1:nrow(data2015_2016),v,label = FALSE)[sample(1:nrow(data2015_2016))]
  print(grps)
  pred = lapply(1:v,function(i,data2015_2016,cl,k){omit = which(grps == i)
  pcl = knn(data2015_2016[-omit,],data2015_2016[omit,],cl[-omit],k=k)
  },data2015_2016,cl,k)
  wh = unlist(pred)
  table(wh,cl[order(grps)])
}
vknn(5,data2015_2016[1:4],data2015_2016$BPXSY1,5)
```

```{r}
## RandomForest

ind <- sample(2,nrow(data2015_2016),replace = TRUE,prob = c(0.7, 0.3))

set.seed(123)
train <- data2015_2016[ind == 1, ]
test <- data2015_2016[ind == 2, ]
str(train)
str(test)

```

```{r}
train$BPXSY1_1 <- as.factor(train$BPXSY1_1)
ntree_fit <- randomForest(BPXSY1_1~., data = train, mtry = 2, ntree = 400)
plot(ntree_fit)
```

```{r}
rf <- randomForest(BPXSY1_1~., data = train, mtry = 2, ntree = 400, importance = TRUE)
importance <- importance(x=rf)
rf
importance
```

```{r}
varImpPlot(rf)
```

```{r}
pred1 <- predict(rf,data=train)

Freq1 <- table(pred1,train$BPXSY1_1)

sum(diag(Freq1))/sum(Freq1)
```

```{r}
plot(margin(rf,test$BPXSY1_1))
```

```{r}
## Lasso Regression
```

```{r}
x_var <- model.matrix(BPXSY1~., data2015_2016)[,-1]
y_var <- data2015_2016$BPXSY1
```

```{r}
set.seed(123)
train <- sample(1:nrow(x_var), nrow(x_var)/2)

x_train <- x_var[train, ]
y_train <- y_var[train]

x_test <- x_var[-train, ]
y_test <- y_var[-train]
```

```{r}
lambda_seq <- 10^seq(2, -2, by = -.1)
```

```{r}
cv_output <- cv.glmnet(x_train, y_train, alpha = 1, lambda = lambda_seq, family='gaussian')
best_lam <- cv_output$lambda.min
lasso_best <- glmnet(x_train, y_train, alpha = 1, lambda = best_lam, family='gaussian')
coef(lasso_best)
```

```{r}
preds <- predict(lasso_best, s = best_lam, newx = x_test)
rss <- sum((preds - y_test) ^ 2)
tss <- sum((y_test - mean(y_test))^2)
rsq <- 1 - rss/tss
rsq
```
